enum Selection {
    CATEGORY = "UPDATE_CATEGORY_SELECTION",
    SUB_CATEGORY = "UPDATE_SUB_CATEGORY_SELECTION",
    PROVINCE = "UPDATE_PROVINCE_SELECTION",
    PRICE = "UPDATE_PRICE_RANGE_SELECTION",
    SEARCH = "UPDATE_SEARCH_SELECTION",
    FILTER = "UPDATE_IS_FILTER_OPEN_SELECTION"
}

export default Selection